/// <reference types="wxt/env" />
/// <reference types="vite/client" />

import 'wxt/browser';

declare module '*.css' {
  const classes: Record<string, string>;
  export default classes;
}

// Augment WXT's browser runtime to expose getURL, which exists at runtime
// Keep in sync with .wxt/types/paths.d.ts which is generated by WXT
declare module 'wxt/browser' {
  interface WxtRuntime {
    getURL(path: string): string;
  }
}
